spring.application.name=employeeManagementSystem
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/employee?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Defines the URL to access the OpenAPI JSON documentation
springdoc.api-docs.path=/api-docs
# Defines the URL to access the Swagger UI interface (web interface to test the documentation)
springdoc.swagger-ui.path=/swagger-ui/v1/employeeManagementSystem
# Sorts route groups (tags) alphabetically in Swagger UI
springdoc.swagger-ui.tagsSorter=alpha
# Sorts operations (endpoints) by HTTP method (GET, POST, PUT, DELETE)
springdoc.swagger-ui.operationsSorter=method





